dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $REPO_NAME .
      - docker images
      - docker tag $REPO_NAME $DOCKER_USERNAME/$REPO_NAME
      - docker push $DOCKER_USERNAME/$REPO_NAME
    - stage: test
      script: - docker run --rm $DOCKER_USERNAME/$REPO_NAME 

