sudo: true
dist: trusty

language: python
python:
  - 2.7

services:
  - docker


 branches:
  only:
    - "master"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  - docker images
  
before_script:
  - image="$REPO_NAME"

script:
  - docker build -t ${image} .
  - docker tag ${image} $DOCKER_USERNAME/${image}
  - docker images
 
after_script:
  - docker run --rm $DOCKER_USERNAME/${image} 
  - docker run --rm $DOCKER_USERNAME/${image} 
  - docker images 
# vim:set et ts=2 sw=2:  

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push /$DOCKER_USERNAME/${image}

notifications: 
  slack:
    rooms:
      - ${SLACK_TOKEN}
    on_success: always # default: always
    on_failure: always # default: always  
