sudo: required

services:
  - docker

script:
  - docker build -t $REPO_NAME .
  - docker tag $REPO_NAME $DOCKER_USERNAME/$REPO_NAME
  - docker images
  - docker run --rm $DOCKER_USERNAME/$REPO_NAME 
  - docker run --rm $DOCKER_USERNAME/$REPO_NAME 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$REPO_NAME

notifications: 
  slack:
    rooms:
      - ${SLACK_TOKEN}
    on_success: always # default: always
    on_failure: always # default: always 
